# This file may be used to create an environment using:
# $ conda env create --file environment.yml
# platform: linux-64
name: HLA-typing
channels:
  - bioconda
  - conda-forge
dependencies:
  - peppy>=0.35
  - pytest-workflow>=1.6.0
  - snakemake-minimal=7.32
  - snakefmt=0.10.0
