# This file may be used to create an environment using:
# $ conda env create --file environment.yml
# platform: linux-64
name: HLA-typing
channels:
  - bioconda
  - conda-forge
dependencies:
  - peppy>=0.40
  - pytest-workflow>=2.0
  - snakemake-minimal>=8.4
  - snakefmt>=0.10
